# docker/docker-compose.yml
version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: adcampaign
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
